### ISSUE TITLE
'xrange' is not defined

### ISSUE THREAD

**Issue by ShreyaKashi** [genomexyz/detect_object#1]
After running the script 'drawbox.py' I'm getting an error

> 342 88 679 456 600 1024
> 1
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 67, in saveboxcord
>     for i in xrange(len(self.allcord)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 103, in previmg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> 577 305 681 292 600 1024
> 2
> 803 133 955 307 600 1024
> 3
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 67, in saveboxcord
>     for i in xrange(len(self.allcord)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 103, in previmg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/edpo/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "drawbox.py", line 90, in nextimg
>     for i in xrange(len(self.allrect)):
> NameError: name 'xrange' is not defined

After exiting the image, the box.csv file is empty.

**Comment by ShreyaKashi** [comment]
The error occurred because I was using Python3. 
I added the following piece of code suggested by Martijn Pieters [https://stackoverflow.com/questions/17192158/nameerror-global-name-xrange-is-not-defined-in-python-3](url) and it worked fine.


```
try:
    # Python 2 forward compatibility
    range = xrange
except NameError:
    pass
```
